"""empty message

Revision ID: 2a431de47164
Revises: 
Create Date: 2026-03-25 13:42:49.018499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2a431de47164'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestamos')
    with op.batch_alter_table('cuentas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cuenta_numero'))

    op.drop_table('cuentas')
    op.drop_table('roles')
    op.drop_table('telefonos')
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pago_fecha'))

    op.drop_table('pagos')
    op.drop_table('usuarios')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cliente_dpi'))

    op.drop_table('clientes')
    op.drop_table('direcciones')
    op.drop_table('bitacora')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora',
    sa.Column('id_log', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('fk_bitacora_usuario'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_log', name=op.f('bitacora_pkey'))
    )
    op.create_table('direcciones',
    sa.Column('id_direccion', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name=op.f('fk_direccion_cliente'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_direccion', name=op.f('direcciones_pkey'))
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dpi', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.Column('nombres', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellidos', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('fk_cliente_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cliente', name=op.f('clientes_pkey')),
    sa.UniqueConstraint('dpi', name=op.f('clientes_dpi_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('id_usuario', name=op.f('clientes_id_usuario_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cliente_dpi'), ['dpi'], unique=False)

    op.create_table('usuarios',
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id_rol', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], name=op.f('fk_usuario_rol')),
    sa.PrimaryKeyConstraint('id_usuario', name=op.f('usuarios_pkey')),
    sa.UniqueConstraint('username', name=op.f('usuarios_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('pagos',
    sa.Column('id_pago', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_prestamo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monto', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('fecha_pago', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_prestamo'], ['prestamos.id_prestamo'], name=op.f('fk_pago_prestamo'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_pago', name=op.f('pagos_pkey'))
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pago_fecha'), ['fecha_pago'], unique=False)

    op.create_table('telefonos',
    sa.Column('id_telefono', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name=op.f('fk_telefono_cliente'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_telefono', name=op.f('telefonos_pkey'))
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_rol', name=op.f('roles_pkey')),
    sa.UniqueConstraint('nombre', name=op.f('roles_nombre_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('cuentas',
    sa.Column('id_cuenta', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero_cuenta', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('tipo_cuenta', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('saldo', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.CheckConstraint("tipo_cuenta::text = ANY (ARRAY['Ahorro'::character varying, 'Monetaria'::character varying]::text[])", name=op.f('cuentas_tipo_cuenta_check')),
    sa.CheckConstraint('saldo >= 0::numeric', name=op.f('cuentas_saldo_check')),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name=op.f('fk_cuenta_cliente'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_cuenta', name=op.f('cuentas_pkey')),
    sa.UniqueConstraint('numero_cuenta', name=op.f('cuentas_numero_cuenta_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('cuentas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cuenta_numero'), ['numero_cuenta'], unique=False)

    op.create_table('prestamos',
    sa.Column('id_prestamo', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monto_aprobado', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('saldo_pendiente', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('tasa_interes', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('plazo_meses', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Activo'::character varying"), autoincrement=False, nullable=False),
    sa.CheckConstraint("estado::text = ANY (ARRAY['Activo'::character varying, 'Pagado'::character varying, 'Mora'::character varying]::text[])", name=op.f('prestamos_estado_check')),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name=op.f('fk_prestamo_cliente'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_prestamo', name=op.f('prestamos_pkey'))
    )
    # ### end Alembic commands ###
